### ISSUE TITLE
Unknown server OS

### ISSUE THREAD

**Issue by pkuntz2** [git-artes/docker-gnuradio#11]
This error is outputted when running the container

```
docker run --net=host --env="DISPLAY" --volume="$HOME/.Xauthority:/root/.Xauthority:rw" --device /dev/snd -v persistent:/home/gnuradio/persistent --device /dev/dri -v /dev/bus/usb/:/dev/bus/usb/ --privileged --group-add=audio -it ubuntu:gnuradio-releases bash
docker: unknown server OS: .
See 'docker run --help'.
```

**Comment by git-artes** [comment]
This is a problem with your docker installation. You should perform the post-installation instructions to allow docker to be run without sudo privileges. See for instance the discussion here: https://github.com/Xilinx/Vitis-AI/issues/18.
