### ISSUE TITLE
I was prompted for datetime zone during build

### ISSUE THREAD

**Issue by abusous2000** [git-artes/docker-gnuradio#5]
Many thanks for putting this together
It worked like a charm

However, as I was building the image
I was promoted to enter the timezone
but I could not enter it

However, once I uncommented this line👇
https://github.com/git-artes/docker-gnuradio/blob/master/gnuradio-releases/Dockerfile#L4
it worked like a charm

Many thx again

**Comment by git-artes** [comment]
Thanks! I'll do just that.
