### ISSUE TITLE
question to saving my project

### ISSUE THREAD

**Issue by sweethomer** [git-artes/docker-gnuradio#7]
Hey, sorry maybe for dumb question im new in docker and docking. So how do I save my project? Because it save it, but when I exit the docker (return to my home environment) and then when i want to go back with that command ("docker run --net=host --env="DISPLAY" --volume="$HOME/.Xauthority:/root/.Xauthority:rw" --privileged -v /dev/bus/usb/:/dev/bus/usb/ --device /dev/snd -v persistent-37:/home/gnuradio/persistent --group-add=audio -it ubuntu:gnuradio-releases-3.7 bash") it isnt saving my data. Thanks for your response and have a nice day :)

**Comment by git-artes** [comment]
Hi,
As explained in the README, all files that are not in the /home/gnuradio/persistent directory are erased when you exit the container. You should save your work there. 
best
